# schema.yml

version: 2

sources:
    - name: staging 
      database: driven-utility-411313 
      schema:  ny_taxi

      tables:
          - name:  green_cab_data
          - name:  yellow_cab_data